# Generated by Django 4.2.5 on 2024-09-08 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productrating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductRating',
        ),
        migrations.AlterUniqueTogether(
            name='ingredientreview',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='harmfulingredient',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='harmfulingredient',
            name='description',
        ),
        migrations.AddField(
            model_name='harmfulingredient',
            name='harmful',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='harmfulingredient',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ingredientreview',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.harmfulingredient'),
        ),
        migrations.AlterField(
            model_name='ingredientreview',
            name='rating',
            field=models.PositiveIntegerField(),
        ),
    ]
