# Generated by Django 4.2.5 on 2024-09-09 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0006_ingredient_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.RenameField(
            model_name='productrating',
            old_name='ingredients',
            new_name='review',
        ),
        migrations.AddField(
            model_name='ingredientreview',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productrating',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productrating',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredientreview',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='product.harmfulingredient'),
        ),
        migrations.AlterField(
            model_name='ingredientreview',
            name='rating',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
        migrations.AlterField(
            model_name='productrating',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterUniqueTogether(
            name='ingredientreview',
            unique_together={('ingredient', 'user')},
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
