# Generated by Django 4.2.5 on 2024-09-13 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
