# Generated by Django 5.1.2 on 2024-10-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='harmfulingredient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
